
// 一些默认的参数
export default {
    DEFAULT_COLOR                         : 0xFF8C00,
    DEFAULT_POINT_SIZE                    : 24,
    DEFAULT_POINT_FEATHER                 : 3,
    DEFAULT_LINE_WIDTH                    : 1.6,
    DEFAULT_LINE_LENGTH                   : 20,
    DEFAULT_CIRCLE_RADIUS                 : 1,
    DEFAULT_CIRCLE_RADIUS_SEGMENTS        : 36,

    DEFAULT_SHADOW_CAMERA_NEAR            : 0.1,
    DEFAULT_SHADOW_CAMERA_FAR             : 200,
    DEFAULT_SHADOW_CAMERA_RIGHT           : +20,
    DEFAULT_SHADOW_CAMERA_LEFT            : -20,
    DEFAULT_SHADOW_CAMERA_TOP             : +20,
    DEFAULT_SHADOW_CAMERA_BOTTOM          : -20,
    DEFAULT_SHADOW_CAMERA_MAPSIZE_WIDTH   : 1024,
    DEFAULT_SHADOW_CAMERA_MAPSIZE_HEIGHT  : 1024,
    DEFAULT_SHADOW_CAMERA_RADIUS          : 4,
    DEFAULT_SHADOW_CAMERA_BIAS_LIGHT_POINT: -0.00050,
    DEFAULT_SHADOW_CAMERA_BIAS_LIGHT_SPOT : -0.00050,
    DEFAULT_SHADOW_CAMERA_BIAS_LIGHT_DIR  : -0.00050,
}
